# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservist',
            name='comment',
            field=models.TextField(default='Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservist',
            name='email',
            field=models.EmailField(default='email', max_length=254),
            preserve_default=False,
        ),
    ]
