# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_auto_20170320_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='categories',
        ),
    ]
