# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_stage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='deadline',
            field=models.DateField(default='2017-05-17'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Этап'),
        ),
    ]
