# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20170320_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservist',
            name='birtday',
        ),
        migrations.AddField(
            model_name='reservist',
            name='birthday',
            field=models.DateField(default='1984-04-16', verbose_name='date of birth'),
            preserve_default=False,
        ),
    ]
