# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_auto_20170320_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservist',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservists', to='academic.Status'),
        ),
    ]
