# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_auto_20170321_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='categories',
            field=models.ManyToManyField(to='academic.Category'),
        ),
    ]
