# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_stage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='statuses',
            field=models.ManyToManyField(to='academic.Status'),
        ),
    ]
