# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_auto_20170322_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='stages',
        ),
        migrations.RemoveField(
            model_name='reservist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='reservist',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='section',
        ),
        migrations.AddField(
            model_name='reservist',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservists', to='academic.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='stages',
            field=models.ManyToManyField(to='academic.Stage'),
        ),
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic.Category'),
        ),
        migrations.AlterField(
            model_name='section',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic.Status'),
        ),
    ]
