# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_reservist_stages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Конкурсная категория', 'verbose_name_plural': 'Конкурсные категории'},
        ),
        migrations.AlterModelOptions(
            name='reservist',
            options={'verbose_name': 'Участник программы', 'verbose_name_plural': 'Участники программы'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Этап участия', 'verbose_name_plural': 'Этапы участия'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус участия', 'verbose_name_plural': 'Статусы участия'},
        ),
        migrations.AddField(
            model_name='stage',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файд шаблона'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='stages',
            field=models.ManyToManyField(blank=True, editable=False, related_name='reservists', to='academic.Stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='deadline',
            field=models.DateField(verbose_name='Крайний срок'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
