# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_auto_20170322_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservist',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='stage',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='report_templates', verbose_name='Файд шаблона'),
        ),
    ]
