# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_reservist_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservist',
            name='birthdate',
        ),
    ]
