# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_reservist_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservist',
            name='personal_page',
            field=models.URLField(default='https://hse.ru'),
            preserve_default=False,
        ),
    ]
