# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_auto_20170323_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dept_code',
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='academic.Department'),
        ),
    ]
