# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_auto_20170323_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='reservist',
            name='phd',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения учёной степени (если есть)'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Department', verbose_name='Основное место работы'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='position',
            field=models.CharField(default='Сотрудник', max_length=200, verbose_name='Должность'),
        ),
    ]
