# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0025_auto_20170323_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservist',
            name='hse',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала работы в ВШЭ'),
            preserve_default=False,
        ),
    ]
