# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0026_reservist_hse'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='departments',
            field=models.ManyToManyField(to='academic.Department'),
        ),
    ]
