# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0027_stage_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Category', verbose_name='Конкурсная категория'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Department', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='personal_page',
            field=models.URLField(blank=True, verbose_name='Личная страница'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='phd',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения учёной степени'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='position',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservists', to='academic.Status', verbose_name='Статус участия'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='categories',
            field=models.ManyToManyField(to='academic.Category', verbose_name='Конкурсные категории'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='departments',
            field=models.ManyToManyField(to='academic.Department', verbose_name='Подразделения'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='statuses',
            field=models.ManyToManyField(to='academic.Status', verbose_name='Статусы участников'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='report_templates', verbose_name='Шаблон отчёта'),
        ),
    ]
