# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0028_auto_20170331_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservist',
            old_name='stages',
            new_name='current_stages',
        ),
    ]
