# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0029_auto_20170331_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('consolidated', models.BooleanField()),
                ('template_file', models.FileField(blank=True, null=True, upload_to='report_templates', verbose_name='Шаблон отчёта')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='template_file',
        ),
        migrations.AddField(
            model_name='department',
            name='manager_email',
            field=models.EmailField(default='null@hse.ru', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='manager_name',
            field=models.CharField(default='NULL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='academic.Stage'),
        ),
    ]
