# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0030_auto_20170402_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservist',
            name='current_stages',
        ),
        migrations.AddField(
            model_name='participation',
            name='reservist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Reservist'),
        ),
        migrations.AddField(
            model_name='participation',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Stage'),
        ),
        migrations.AddField(
            model_name='participation',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Step'),
        ),
        migrations.AddField(
            model_name='reservist',
            name='steps',
            field=models.ManyToManyField(through='academic.Participation', to='academic.Step'),
        ),
    ]
