# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_auto_20170404_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.Step'),
            preserve_default=False,
        ),
    ]
