# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0035_auto_20170412_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRequirment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('hse', 'Начало работы'), ('phd', 'Присвоение учёной степени'), ('bth', 'Рождение')], max_length=3, verbose_name='Дата')),
                ('threshold_min', models.DateField(blank=True, null=True)),
                ('threshold_max', models.DateField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Stage')),
            ],
        ),
    ]
