# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0037_auto_20170413_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stageset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.StageSet'),
        ),
    ]
