# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0038_auto_20170413_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stagename',
            field=models.CharField(default='iq', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='stageset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.StageSet'),
        ),
    ]
