# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0039_auto_20170413_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservist',
            name='degree',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Degree'),
        ),
    ]
