# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0041_auto_20170413_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='stageset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='academic.StageSet'),
            preserve_default=False,
        ),

        migrations.RemoveField(
            model_name='step',
            name='template_consolidated',
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('name', 'stageset')]),
        ),
    ]
