# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0042_auto_20170414_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='stage',
        ),
    ]
