# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0043_remove_step_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='statuses',
        ),
        migrations.AddField(
            model_name='stageset',
            name='statuses',
            field=models.ManyToManyField(to='academic.Status', verbose_name='Статусы участников'),
        ),
    ]
