# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0044_auto_20170414_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='name_by',
            field=models.CharField(default='A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='name_to',
            field=models.CharField(default='B', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='reservists',
            field=models.ManyToManyField(through='academic.Participation', to='academic.Reservist'),
        ),
    ]
