# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0045_auto_20170414_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='manager_position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stage',
            name='manager_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name_to',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
