# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0046_auto_20170414_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='report_templates', verbose_name='Шаблон отчёта')),
            ],
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name': 'Учёная степень', 'verbose_name_plural': 'Учёные степени'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='stageset',
            options={'verbose_name': 'Группа этапов', 'verbose_name_plural': 'Группы этапов'},
        ),
        migrations.RemoveField(
            model_name='step',
            name='template_file',
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='stageset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='academic.StageSet'),
        ),
    ]
