# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0047_auto_20170414_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager_email',
        ),
        migrations.RemoveField(
            model_name='department',
            name='manager_name',
        ),
        migrations.AlterField(
            model_name='reservist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Category', verbose_name='Конкурсная категория'),
        ),
    ]
