# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0048_auto_20170417_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daterequirment',
            options={'verbose_name': 'Формальное требование', 'verbose_name_plural': 'Формальные требования'},
        ),
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'permissions': (('reports', 'Can make reports'),), 'verbose_name': 'Шаблон отчёта', 'verbose_name_plural': 'Шаблоны отчётов'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ('deadline',), 'verbose_name': 'Этап участия', 'verbose_name_plural': 'Этапы участия'},
        ),
        migrations.AlterField(
            model_name='daterequirment',
            name='field',
            field=models.CharField(choices=[('hse', 'Дата начала работы'), ('phd', 'Дата присвоения учёной степени'), ('bth', 'Дата рождения')], max_length=3, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='daterequirment',
            name='threshold_max',
            field=models.DateField(blank=True, null=True, verbose_name='Максимум'),
        ),
        migrations.AlterField(
            model_name='daterequirment',
            name='threshold_min',
            field=models.DateField(blank=True, null=True, verbose_name='Минимум'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='academic.Department', verbose_name='Вышестоящее подразделение'),
        ),
        migrations.AlterField(
            model_name='department',
            name='quota',
            field=models.IntegerField(default=4, verbose_name='Квота на участие'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='report_templates', verbose_name='Файл шаблона'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='degree',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Degree', verbose_name='Учёная степень'),
        ),
        migrations.AlterField(
            model_name='reservist',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Position', verbose_name='Должность'),
        ),
    ]
