# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0049_auto_20170417_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_quoted',
            field=models.BooleanField(default=True, verbose_name='Квотирование участников'),
        ),
    ]
