# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0050_category_is_quoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
