# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='is_final',
            field=models.BooleanField(default=False, verbose_name='Является финальным'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='/Users/victor/workspace/faculty/report_templates', verbose_name='Файл шаблона'),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
