# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20170428_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Сокращённое название'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='report_templates', verbose_name='Файл шаблона'),
        ),
    ]
