# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20170510_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterequirment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daterequirment',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.Status'),
            preserve_default=False,
        ),
    ]
