# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20171027_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_quoted',
            field=models.BooleanField(default=True, verbose_name='Квотирование участников'),
        ),
    ]
