# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_auto_20170519_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daterequirment',
            unique_together=set([('field', 'category', 'status')]),
        ),
    ]
