# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_auto_20170519_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daterequirment',
            name='stage',
        ),
    ]
