# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_remove_daterequirment_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='daterequirment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
