DEFAULT_FROM_EMAIL="Admin <admin@hse.ru>"
EMAIL_HOST='smtp.hse.ru'
EMAIL_PORT=465
EMAIL_HOST_USER='admin@hse.ru'
EMAIL_HOST_PASSWORD=''
EMAIL_USE_TLS=False
EMAIL_USE_SSL=True
EMAIL_SSL_KEYFILE=None
EMAIL_SSL_CERTFILE=None
EMAIL_TIMEOUT=10

EMAIL_SUBJECT_PREFIX="Академический резерв"
